# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Convertdate < Formula
  desc "Software to convert AD and BS dates"
  homepage "https://github.com/Ulleri-Tech/nepali-date-cli"
  version "0.9"
  license "MIT"

  on_macos do
    url "https://github.com/Ulleri-Tech/nepali-date-cli/releases/download/v0.9/nepali-date-cli_0.9_darwin_all.tar.gz"
    sha256 "60f558210e449e7747b04cb8e8b1687bcf001a26c0185179e5e1c93227c81a99"

    def install
      bin.install "convertdate"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Ulleri-Tech/nepali-date-cli/releases/download/v0.9/nepali-date-cli_0.9_linux_armv6.tar.gz"
      sha256 "f32a5c779f7057c4696cd8073b2eee62eef6c685e6065228da9e2062580074c3"

      def install
        bin.install "convertdate"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Ulleri-Tech/nepali-date-cli/releases/download/v0.9/nepali-date-cli_0.9_linux_amd64.tar.gz"
      sha256 "e5343e11c338fe96113ff0519b255f7e00a6c7d7b59c43674ed46610e6d33bee"

      def install
        bin.install "convertdate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Ulleri-Tech/nepali-date-cli/releases/download/v0.9/nepali-date-cli_0.9_linux_arm64.tar.gz"
      sha256 "ff5db455990c3446a0d76f6be1cb3bdaef877820e0fd5881c85af5bc01c4087d"

      def install
        bin.install "convertdate"
      end
    end
  end
end
