# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Convertdate < Formula
  desc ""
  homepage "https://github.com/Ulleri-Tech/nepali-date-cli"
  version "0.5-SNAPSHOT-dc22856"

  on_macos do
    url 
"https://github.com/Ulleri-Tech/nepali-date-cli/releases/download/v0.5/nepali-date-cli_0.5-SNAPSHOT-dc22856_darwin_all.tar.gz"
    sha256 "7409ccabf1b7f51cdb60da81a50f1f014756a3a36a63ccfdf37795d0b8c9e31b"

    def install
      bin.install "nepali-date-cli"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url 
"https://github.com/Ulleri-Tech/nepali-date-cli/releases/download/v0.5/nepali-date-cli_0.5-SNAPSHOT-dc22856_linux_armv6.tar.gz"
      sha256 "685725f3f7df34b731bc3ce806fa4b8487016bf20764d4bc33b04833e6e61c4b"

      def install
        bin.install "convertdate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url 
"https://github.com/Ulleri-Tech/nepali-date-cli/releases/download/v0.5/nepali-date-cli_0.5-SNAPSHOT-dc22856_linux_arm64.tar.gz"
      sha256 "b1b3c1001ceaa0eb68776e582aed0e4aba235935ba5f5a6de60d926a7d188a8a"

      def install
        bin.install "convertdate"
      end
    end
    if Hardware::CPU.intel?
      url 
"https://github.com/Ulleri-Tech/nepali-date-cli/releases/download/v0.5/nepali-date-cli_0.5-SNAPSHOT-dc22856_linux_amd64.tar.gz"
      sha256 "45864c0a81363ddb92c7550b36bf037804f07513eb11a56dbccd4cfcc2cf17f3"

      def install
        bin.install "convertdate"
      end
    end
  end
end

