# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Convertdate < Formula
  desc ""
  homepage "https://github.com/Ulleri-Tech/nepali-date-cli"
  version "0.8"

  on_macos do
    url "https://github.com/Ulleri-Tech/nepali-date-cli/releases/download/v0.8/nepali-date-cli_0.8_darwin_all.tar.gz"
    sha256 "3689fbc63211e30832dc90eb0958905d90ab69690ff9b137292840e68b55d99e"

    def install
      bin.install "nepali-date-cli"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Ulleri-Tech/nepali-date-cli/releases/download/v0.8/nepali-date-cli_0.8_linux_arm64.tar.gz"
      sha256 "a57fac497ddb76ca7132c9beca5fc4a1d697a127f66f301378854c4e4205c9d2"

      def install
        bin.install "convertdate"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Ulleri-Tech/nepali-date-cli/releases/download/v0.8/nepali-date-cli_0.8_linux_amd64.tar.gz"
      sha256 "c44ea6daafbbe9c2b9fa5a15c3d59a07f89d58ea907ef1e5dbf93a6e0ddc4209"

      def install
        bin.install "convertdate"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Ulleri-Tech/nepali-date-cli/releases/download/v0.8/nepali-date-cli_0.8_linux_armv6.tar.gz"
      sha256 "f530130bb7f3d3fb5b968e14dedb742a0a589f7d294e367063538aaa2e1146dd"

      def install
        bin.install "convertdate"
      end
    end
  end
end
